#!/usr/bin/env cwl-runner

# (Re)generated by BlueBee Platform

$namespaces:
  bb: http://bluebee.com/cwl/
  ilmn-tes: http://platform.illumina.com/rdf/iap/
cwlVersion: v1.0
class: CommandLineTool
bb:toolVersion: '1'
requirements:
- class: InlineJavascriptRequirement
- class: ShellCommandRequirement
hints:
- class: ResourceRequirement
  coresMin: 1
  ramMin: 10
- class: ResourceRequirement
  ilmn-tes:resources:
    tier: standard
    type: standardHiCpu
    size: small
- class: DockerRequirement
  dockerPull: clinical_metagenomics_preprocessing:latest
label: awk
doc: pattern scanning and processing with awk
inputs:
  field_separator:
    type:
    - string
    - 'null'
    doc: string that separaters fields on a line
    inputBinding:
      prefix: -F
  inherit_format:
    type:
    - boolean
    - 'null'
    doc: copy format from target_files input to result output
  program:
    type: string
    doc: AWK program
    inputBinding:
      prefix: -e
  target_files:
    type:
      type: array
      items: File
    doc: files to apply program to
    streamable: true
    inputBinding:
      position: 100
  variable_setting:
    type:
    - type: array
      items: string
    - 'null'
    doc: one or more strings of the format VAR=VALUE to set VAR to VALUE
    inputBinding:
      prefix: -v
outputs:
  result:
    type: File
    outputBinding:
      glob:
      - outfile
arguments:
- position: 200
  prefix: '> '
  valueFrom: outfile
  shellQuote: false
baseCommand:
- awk
