#!/usr/bin/env cwl-runner

# (Re)generated by BlueBee Platform

$namespaces:
  bb: http://bluebee.com/cwl/
  ilmn-tes: http://platform.illumina.com/rdf/iap/
cwlVersion: cwl:v1.0
class: CommandLineTool
bb:toolVersion: '1'
id: bam2fastq
requirements:
- class: InlineJavascriptRequirement
hints:
- class: DockerRequirement
  dockerPull: clinical_metagenomics_preprocessing:latest
- class: ResourceRequirement
  ilmn-tes:resources:
    tier: standard
    type: standardHiCpu
    size: small
label: bam2fastq
stderr: stderr.txt
inputs:
  bam:
    type: File
    inputBinding:
      position: 1
      prefix: -i
outputs:
  fastq_r1:
    type: File
    outputBinding:
      glob:
      - '*.R1.fastq'
  fastq_r2:
    type: File
    outputBinding:
      glob:
      - '*.R2.fastq'
  error_log:
    type: stderr
arguments:
- position: 2
  prefix: -fq
  valueFrom: $(inputs.bam.nameroot + ".R1.fastq")
- position: 3
  prefix: -fq2
  valueFrom: $(inputs.bam.nameroot + ".R2.fastq")
baseCommand:
- bedtools
- bamtofastq
