#!/usr/bin/env cwl-runner

# (Re)generated by BlueBee Platform

$namespaces:
  bb: http://bluebee.com/cwl/
  ilmn-tes: http://platform.illumina.com/rdf/iap/
cwlVersion: cwl:v1.0
class: CommandLineTool
bb:toolVersion: '1'
requirements:
- class: InlineJavascriptRequirement
- class: ShellCommandRequirement
hints:
- class: DockerRequirement
  dockerPull: clinical_metagenomics_preprocessing:latest
- class: ResourceRequirement
  ilmn-tes:resources:
    tier: standard
    type: standardHiCpu
    size: small
label: blastn
stderr: stderr.txt
inputs:
  db:
    type: Directory
    inputBinding:
      position: 0
      prefix: -db
      valueFrom: $(self.path + "/" + self.basename)
  query_fasta:
    type: File
    inputBinding:
      position: 1
      prefix: -query
  evalue:
    type:
    - float
    - 'null'
    inputBinding:
      position: 4
      prefix: -evalue
  max_target_seqs:
    type:
    - int
    - 'null'
    inputBinding:
      position: 4
      prefix: -max_target_seqs
  max_hsps:
    type:
    - int
    - 'null'
    inputBinding:
      position: 5
      prefix: -max_hsps
  num_alignments:
    type:
    - int
    - 'null'
    inputBinding:
      position: 3
      prefix: -num_alignments
  culling_limit:
    type:
    - int
    - 'null'
    inputBinding:
      position: 5
      prefix: -culling_limit
outputs:
  result:
    type: File
    outputBinding:
      glob:
      - blast_result.txt
  error_log:
    type: stderr
arguments:
- position: 2
  prefix: -outfmt
  valueFrom: '6'
- position: 6
  prefix: -num_threads
  valueFrom: \$(nproc --all)
  shellQuote: false
- position: 7
  prefix: -out
  valueFrom: blast_result.txt
baseCommand:
- blastn
