#!/usr/bin/env cwl-runner

# (Re)generated by BlueBee Platform

$namespaces:
  bb: http://bluebee.com/cwl/
  ilmn-tes: http://platform.illumina.com/rdf/iap/
cwlVersion: cwl:v1.0
class: CommandLineTool
bb:toolVersion: '1'
requirements:
- class: InlineJavascriptRequirement
- class: ShellCommandRequirement
hints:
- class: ResourceRequirement
  ilmn-tes:resources:
    tier: standard
    type: standardHiCpu
    size: small
- class: DockerRequirement
  dockerPull: clinical_metagenomics_preprocessing:latest
label: diamond
stderr: stderr.txt
inputs:
  db:
    type: File
    inputBinding:
      position: 0
      prefix: -d
  query_fasta:
    type: File
    inputBinding:
      position: 1
      prefix: -q
  output_fmt:
    type: int
    default: 6
    inputBinding:
      position: 3
      prefix: -f
  max_target_seqs:
    type:
    - int
    - 'null'
    default: 10
    inputBinding:
      position: 4
      prefix: -k
  evalue:
    type: float
    default: 1
    inputBinding:
      position: 6
      prefix: -e
outputs:
  result:
    type: File
    outputBinding:
      glob:
      - diamond_result.txt
  error_log:
    type: stderr
arguments:
- position: 6
  prefix: -p
  valueFrom: \$(nproc --all)
  shellQuote: false
- position: 5
  valueFrom: -sensitive
- prefix: --out
  valueFrom: diamond_result.txt
baseCommand:
- diamond
- blastx
