#!/usr/bin/env cwl-runner

# (Re)generated by BlueBee Platform

$namespaces:
  bb: http://bluebee.com/cwl/
  ilmn-tes: http://platform.illumina.com/rdf/iap/
cwlVersion: cwl:v1.0
class: CommandLineTool
bb:toolVersion: '1'
id: samtools sort
requirements:
- class: ShellCommandRequirement
hints:
- class: DockerRequirement
  dockerPull: clinical_metagenomics_preprocessing:latest
- class: ResourceRequirement
  ilmn-tes:resources:
    tier: standard
    type: standardHiCpu
    size: small
label: samtools_sort
stderr: stderr.txt
inputs:
  bam:
    type: File
    streamable: true
    inputBinding:
      position: 100
outputs:
  sorted_bam:
    type: File
    streamable: true
    outputBinding:
      glob:
      - '*.sorted.bam'
  error_log:
    type: stderr
arguments:
- position: 2
  prefix: -o
  valueFrom: $(inputs.bam.nameroot).sorted.bam
- position: 1
  prefix: -@
  valueFrom: \$(nproc --all)
  shellQuote: false
baseCommand:
- samtools
- sort
