#!/usr/bin/env cwl-runner

# (Re)generated by BlueBee Platform

$namespaces:
  bb: http://bluebee.com/cwl/
  ilmn-tes: http://platform.illumina.com/rdf/iap/
cwlVersion: cwl:v1.0
class: CommandLineTool
bb:toolVersion: '1'
id: seqtk_subseq
requirements:
- class: InitialWorkDirRequirement
  listing:
  - entry: |-
      #!/bin/bash
      set -euo pipefail
      seqtk subseq $1 $3 > filtered_1.fastq
      seqtk subseq $2 $3 > filtered_2.fastq
    entryname: seqtk.sh
    writable: false
hints:
- class: DockerRequirement
  dockerPull: clinical_metagenomics_preprocessing:latest
- class: ResourceRequirement
  ilmn-tes:resources:
    tier: standard
    type: standardHiCpu
    size: small
label: seqtk_subseq
stderr: stderr.txt
inputs:
  fastq_1:
    type: File
    inputBinding:
      position: 1
  ids:
    type: File
    inputBinding:
      position: 3
  fastq_2:
    type: File
    inputBinding:
      position: 2
outputs:
  filtered_fastq1:
    type: File
    outputBinding:
      glob:
      - filtered_1.fastq
  error_log:
    type: stderr
  filtered_fastq2:
    type: File
    outputBinding:
      glob:
      - filtered_2.fastq
baseCommand:
- bash
- seqtk.sh
